# Generated by Django 3.2 on 2022-03-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='نام پیش\u200cفرض', max_length=100, verbose_name='نام')),
                ('phone', models.CharField(default='9xxxxxxxxx', max_length=10, verbose_name='شماره تلفن')),
                ('massage', models.TextField(default='متن پیام پیش\u200cفرض', max_length=5000, verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام\u200c',
                'verbose_name_plural': 'پیام\u200cهای کاربران',
            },
        ),
    ]
