# Generated by Django 3.2 on 2022-03-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220329_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='base.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='base.school', verbose_name='مدرسه'),
        ),
    ]
