# Generated by Django 3.2 on 2022-03-31 02:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220331_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
