# Generated by Django 3.2 on 2022-03-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_announcement_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
