# Generated by Django 3.2 on 2022-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220401_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masir_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='manzel',
            name='title',
            field=models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان منزل'),
        ),
    ]
