# Generated by Django 3.2 on 2022-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220402_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group',
            name='users',
            field=models.ManyToManyField(to='base.User_Detail', verbose_name='اعضای گروه'),
        ),
    ]
