# Generated by Django 3.2 on 2022-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220408_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='متن پاسخ'),
        ),
    ]
