# Generated by Django 3.2 on 2022-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='club_level',
            field=models.IntegerField(default=0, verbose_name='قرائت\u200cهای انجام شده'),
        ),
    ]
