# Generated by Django 3.2 on 2022-04-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_user_detail_club_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='base/static/club/', verbose_name='فایل')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان فایل')),
                ('level', models.IntegerField(default=0, verbose_name='مرحله')),
                ('verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_files', to='base.user_detail', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فایل\u200c',
                'verbose_name_plural': 'فایل\u200cهای باشگاه',
            },
        ),
    ]
