# Generated by Django 3.2 on 2022-04-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220409_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.TextField(default='پرسش پیش\u200cفرض', max_length=500, verbose_name='متن پرسش')),
                ('O1', models.TextField(default='پاسخ پیش\u200cفرض', max_length=500, verbose_name='گزینه 1')),
                ('O2', models.TextField(default='پاسخ پیش\u200cفرض', max_length=500, verbose_name='گزینه 2')),
                ('O3', models.TextField(default='پاسخ پیش\u200cفرض', max_length=500, verbose_name='گزینه 3')),
                ('O4', models.TextField(default='پاسخ پیش\u200cفرض', max_length=500, verbose_name='گزینه 4')),
                ('A', models.IntegerField(default=1, verbose_name='گزینه صحیح')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش\u200cهای آزمون\u200cهای دانشگاه',
            },
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'صدقه', 'verbose_name_plural': 'صدقات'},
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='نام آزمون')),
                ('questions', models.ManyToManyField(related_name='exams', to='base.Question', verbose_name='پرسش\u200cهای آزمون')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cهای دانشگاه',
            },
        ),
    ]
