# Generated by Django 3.2 on 2022-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_masir_group_achivements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='achivements',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='base.Achivement', verbose_name='دستاوردهای گروه'),
        ),
    ]
