# Generated by Django 3.2 on 2022-04-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_masir_group_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='is_active',
            new_name='is_public',
        ),
    ]
