# Generated by Django 3.2 on 2022-04-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_announcement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='base/static/announcement/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='نمایش برای عموم'),
        ),
    ]
