# Generated by Django 3.2 on 2022-04-11 02:06

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20220411_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='متن پیش\u200cفرض', max_length=1000, verbose_name='متن اعلان')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
            },
        ),
    ]
