# Generated by Django 3.2 on 2022-04-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
