# Generated by Django 3.2 on 2022-04-11 02:29

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_delete_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='مقدار')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charities', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'صدقه',
                'verbose_name_plural': 'صدقات',
            },
        ),
    ]
