# Generated by Django 3.2 on 2022-04-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group',
            name='manzel',
            field=models.IntegerField(default=1, verbose_name='منزل'),
        ),
    ]
