# Generated by Django 3.2 on 2022-04-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_rename_power_manzel_power_for_next_manzel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzel',
            name='food_for_next_manzel',
            field=models.IntegerField(default=0, verbose_name='آذوقه مورد نیاز برای رسیدن به منزل بعدی'),
        ),
        migrations.AlterField(
            model_name='manzel',
            name='power_for_next_manzel',
            field=models.IntegerField(default=0, verbose_name='توان مورد نیاز برای رسیدن به منزل بعدی'),
        ),
    ]
