# Generated by Django 3.2 on 2022-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_faq_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='text',
            field=models.CharField(default='عنوان پیش\u200cفرض', max_length=500, verbose_name='توضیح دستاورد'),
        ),
    ]
