# Generated by Django 3.2 on 2022-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_achivement_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'فعالیت', 'verbose_name_plural': 'فعالیت\u200cها'},
        ),
        migrations.AddField(
            model_name='manzel',
            name='co_title',
            field=models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان معرفتی'),
        ),
    ]
