# Generated by Django 3.2 on 2022-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20220414_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibility',
            name='contact_admin_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به پیام\u200cهای کاربران'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='contact_admin_page_edit',
            field=models.BooleanField(default=False, verbose_name='دسترسی به پیام\u200cهای کاربران'),
        ),
    ]
