# Generated by Django 3.2 on 2022-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20220414_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibility',
            name='announcements_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به اعلانات'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='announcements_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش اعلانات'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='club_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به فایل\u200cهای باشگاه'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='club_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش فایل\u200cهای باشگاه'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='faq_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به پرسش\u200cهای پرتکرار'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='faq_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش پرسش\u200cهای پرتکرار'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='judge_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به اعلانات'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='judge_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش اعلانات'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='reports_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به گزارش\u200cها'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='reports_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش گزارش\u200cها'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='statistics_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به اعلانات'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='statistics_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش اعلانات'),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='contact_admin_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش پیام\u200cهای کاربران'),
        ),
    ]
