# Generated by Django 3.2 on 2022-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20220414_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibility',
            name='statistics_page_edit',
        ),
        migrations.AddField(
            model_name='club_file',
            name='show_public',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='judge_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به داوری فعالیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='judge_page_edit',
            field=models.BooleanField(default=False, verbose_name='ویرایش داوری فعالیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='statistics_page',
            field=models.BooleanField(default=False, verbose_name='دسترسی به آمار'),
        ),
    ]
