# Generated by Django 3.2 on 2022-04-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20220414_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judges', to='base.user_detail', verbose_name='داور'),
        ),
        migrations.AlterField(
            model_name='club_file',
            name='show_public',
            field=models.BooleanField(default=False, verbose_name='نمایش عمومی'),
        ),
    ]
