# Generated by Django 3.2 on 2022-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20220421_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('1', 'ارسال شده'), ('2', 'در حال داوری'), ('3', 'داوری شده و اعلام نشده'), ('4', 'داوری شده'), ('5', 'رد شده و اعلام نشده'), ('6', 'رد شده')], default='1', max_length=1, verbose_name='وضعیت'),
        ),
    ]
