# Generated by Django 3.2 on 2022-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_activity_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='9xxxxxxxxx', max_length=10, verbose_name='شماره تلفن')),
                ('vote_image_1', models.BooleanField(default=False, verbose_name='رای به تصویر اول')),
                ('vote_image_2', models.BooleanField(default=False, verbose_name='رای به تصویر دوم')),
                ('vote_image_3', models.BooleanField(default=False, verbose_name='رای به تصویر سوم')),
                ('vote_image_4', models.BooleanField(default=False, verbose_name='رای به تصویر چهارم')),
                ('vote_image_5', models.BooleanField(default=False, verbose_name='رای به تصویر پنجم')),
                ('vote_music_1', models.BooleanField(default=False, verbose_name='رای به صوت اول')),
                ('vote_music_2', models.BooleanField(default=False, verbose_name='رای به صوت دوم')),
                ('vote_music_3', models.BooleanField(default=False, verbose_name='رای به صوت سوم')),
                ('vote_music_4', models.BooleanField(default=False, verbose_name='رای به صوت چهارم')),
                ('vote_music_5', models.BooleanField(default=False, verbose_name='رای به صوت پنجم')),
                ('vote_video_1', models.BooleanField(default=False, verbose_name='رای به فیلم اول')),
                ('vote_video_2', models.BooleanField(default=False, verbose_name='رای به فیلم دوم')),
                ('vote_video_3', models.BooleanField(default=False, verbose_name='رای به فیلم سوم')),
                ('vote_video_4', models.BooleanField(default=False, verbose_name='رای به فیلم چهارم')),
                ('vote_video_5', models.BooleanField(default=False, verbose_name='رای به فیلم پنجم')),
                ('code', models.IntegerField(default=0, verbose_name='کد تایید')),
                ('is_valid', models.BooleanField(default=False, verbose_name='معتبر')),
            ],
            options={
                'verbose_name': 'رای',
                'verbose_name_plural': 'آرای کاربران',
            },
        ),
    ]
