# Generated by Django 3.2 on 2022-05-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='masood_valid',
            field=models.BooleanField(default=False, verbose_name='نامعتبر معتبر شده بخاطر مسعود!'),
        ),
    ]
