# Generated by Django 3.2 on 2023-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_vote_masood_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_topic',
            name='main',
            field=models.BooleanField(default=False, verbose_name='آیا فعالیت اصلی است؟'),
        ),
    ]
