# Generated by Django 3.2 on 2023-04-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20230401_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_topic',
            name='template',
            field=models.ManyToManyField(blank=True, related_name='templates', to='base.Activity_Template', verbose_name='قالب ها'),
        ),
    ]
