# Generated by Django 3.2 on 2023-04-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20230401_1418'),
        ('base', '0070_activity_topic_template'),
    ]

    operations = [
    ]
