# Generated by Django 3.2 on 2023-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_masir_group_discovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_topic',
            name='code',
            field=models.CharField(blank=True, default='xxxxxxxx', max_length=8, null=True, verbose_name='کد اکتشاف'),
        ),
    ]
