# Generated by Django 3.2 on 2023-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_alter_activity_topic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_topic',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='کد اکتشاف'),
        ),
    ]
