# Generated by Django 3.2 on 2023-04-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_activity_topic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_topic',
            name='level1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='سطح 1'),
        ),
        migrations.AddField(
            model_name='activity_topic',
            name='level2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='سطح 2'),
        ),
        migrations.AddField(
            model_name='activity_topic',
            name='level3',
            field=models.TextField(blank=True, default='', null=True, verbose_name='سطح 3'),
        ),
    ]
