# Generated by Django 3.2 on 2023-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_alter_masir_group_manzel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='manzel',
            field=models.IntegerField(default=1, verbose_name='منزل'),
        ),
    ]
