# Generated by Django 3.2 on 2023-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20230404_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='manzel',
            field=models.IntegerField(default=1, verbose_name='منزل'),
        ),
    ]
