# Generated by Django 3.2 on 2023-04-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_alter_masir_group_manzel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masir_group',
            old_name='is_introduced',
            new_name='introduced',
        ),
    ]
