# Generated by Django 3.2 on 2023-04-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_auto_20230406_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzel',
            name='discover_help',
            field=models.FileField(blank=True, null=True, upload_to='base/static/manzel/', verbose_name='فایل رهنمای اکتشاف'),
        ),
        migrations.AlterField(
            model_name='masir_group',
            name='supergroup',
            field=models.IntegerField(default=1, verbose_name='ابرگروه'),
        ),
    ]
