# Generated by Django 3.2 on 2023-04-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20230407_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='report',
            field=models.TextField(blank=True, default='', null=True, verbose_name='گزارش'),
        ),
    ]
