# Generated by Django 3.2 on 2023-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_achivement_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='نام آزمون')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('Q', models.TextField(default='پرسش پیش\u200cفرض', max_length=5000, verbose_name='متن پرسش')),
                ('O1', models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 1')),
                ('O2', models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 2')),
                ('O3', models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 3')),
                ('O4', models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 4')),
                ('A', models.IntegerField(default=1, verbose_name='گزینه صحیح')),
            ],
            options={
                'verbose_name': 'فراخوان',
                'verbose_name_plural': 'فراخوان ها',
            },
        ),
    ]
