# Generated by Django 3.2 on 2023-04-09 08:43

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_alter_manzel_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'فعالیت', 'verbose_name_plural': 'گروه ها - فعالیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='activity_template',
            options={'verbose_name': 'قالب فعالیت', 'verbose_name_plural': 'فعالیت\u200cها - قالب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='activity_topic',
            options={'verbose_name': 'موضوع فعالیت', 'verbose_name_plural': 'فعالیت\u200cها - موضوعات'},
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'صدقه', 'verbose_name_plural': 'گروه ها - صدقات'},
        ),
        migrations.AlterModelOptions(
            name='club_file',
            options={'verbose_name': 'فایل\u200c', 'verbose_name_plural': 'گروه ها - فایل های باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='masir_group_and_achivement_rel',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'گروه ها - دستاوردها'},
        ),
        migrations.AlterModelOptions(
            name='masir_group_and_exams_rel',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'گروه ها - ارتباط با دانشگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام\u200c', 'verbose_name_plural': 'کاربران - پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'پرسش', 'verbose_name_plural': 'آزمون\u200cهای دانشگاه - پرسش ها'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'گزارش', 'verbose_name_plural': 'گروه ها - گزارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='trash',
            options={'verbose_name': 'اسراف', 'verbose_name_plural': 'گروه ها - اسراف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user_detail',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران - اطلاعات'},
        ),
        migrations.AlterField(
            model_name='event',
            name='Q',
            field=models.TextField(default='پرسش پیش\u200cفرض', max_length=5000, verbose_name='متن فراخوان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='نام فراخوان'),
        ),
        migrations.AlterField(
            model_name='masir_group',
            name='supergroup',
            field=models.IntegerField(default=0, verbose_name='ابرگروه'),
        ),
        migrations.CreateModel(
            name='Masir_Group_And_Event_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('answers', models.CharField(default='', max_length=50, verbose_name='پاسخ\u200cها')),
                ('show_public', models.BooleanField(default=False, verbose_name='نمایش عمومی')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base.event', verbose_name='فراخوان')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'گروه ها - ارتباط با فراخوان ها',
            },
        ),
    ]
