# Generated by Django 3.2 on 2022-03-28 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='پایه')),
                ('city', models.CharField(default='شهر پیش\u200cفرض', max_length=100, verbose_name='نام شهر')),
                ('school', models.CharField(default='مدرسه پیش\u200cفرض', max_length=100, verbose_name='نام مدرسه')),
                ('code', models.CharField(default='شهر پیش\u200cفرض', max_length=5, verbose_name='نام شهر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'اطلاعات کاربران',
            },
        ),
    ]
