# Generated by Django 3.2 on 2022-03-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران',
            },
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='code',
            field=models.CharField(default='xxxxx', max_length=5, verbose_name='کد کاربر'),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='accessibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.accessibility', verbose_name='دسترسی'),
        ),
    ]
