# Generated by Django 3.2 on 2022-03-31 00:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220329_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='منزل چندم', max_length=100, verbose_name='شماره منزل')),
                ('title', models.CharField(default='بدون عنوان', max_length=100, verbose_name='عنوان منزل')),
                ('color', colorfield.fields.ColorField(default='FFFFFF', max_length=18, verbose_name='رنگ پس\u200cزمینه نَوبار')),
                ('top', models.FloatField(default=0, verbose_name='درصد فاصله از بالای نقشه')),
                ('right', models.FloatField(default=0, verbose_name='درصد فاصله از سمت راست نقشه')),
                ('food', models.IntegerField(default=0, verbose_name='آذوقه مورد نیاز')),
                ('power', models.IntegerField(default=0, verbose_name='توان مورد نیاز')),
            ],
        ),
    ]
