# Generated by Django 3.2 on 2022-03-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان اعلان'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش برای عموم'),
        ),
    ]
