# Generated by Django 3.2 on 2022-04-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_masir_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='users',
            field=models.ManyToManyField(related_name='groups', to='base.User_Detail', verbose_name='اعضای گروه'),
        ),
    ]
