# Generated by Django 3.2 on 2022-04-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_masir_group_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='massage',
            new_name='message',
        ),
    ]
