# Generated by Django 3.2 on 2022-04-08 23:36

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_exam_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masir_Group_And_Exams_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('answers', models.CharField(default='', max_length=50, verbose_name='پاسخ\u200cها')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base.exam', verbose_name='آزمون')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط میان گروه\u200cها و آزمون\u200cها',
            },
        ),
    ]
