# Generated by Django 3.2 on 2022-04-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_masir_group_and_exams_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group',
            name='supergroup',
            field=models.IntegerField(default=0, verbose_name='ابرگروه'),
        ),
    ]
