# Generated by Django 3.2 on 2022-04-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_masir_group_supergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان دستاورد')),
                ('image', models.FileField(upload_to='base/static/images/achivement/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاوردها',
            },
        ),
    ]
