# Generated by Django 3.2 on 2022-04-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_achivement'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group',
            name='achivements',
            field=models.ManyToManyField(related_name='groups', to='base.Achivement', verbose_name='دستاوردهای گروه'),
        ),
    ]
