# Generated by Django 3.2 on 2022-04-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_masir_group_achivements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups', to='base.User_Detail', verbose_name='اعضای گروه'),
        ),
    ]
