# Generated by Django 3.2 on 2022-04-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_masir_group_manzel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manzel',
            old_name='food',
            new_name='food_for_next_manzel',
        ),
    ]
