# Generated by Django 3.2 on 2022-04-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20220411_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='base/static/manzel/', verbose_name='فایل توضیحات منزل'),
        ),
        migrations.AddField(
            model_name='manzel',
            name='story',
            field=models.FileField(blank=True, null=True, upload_to='base/static/manzel/', verbose_name='فایل داستان'),
        ),
    ]
