# Generated by Django 3.2 on 2022-04-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20220411_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان قالب')),
                ('type', models.CharField(choices=[('1', 'طلایی'), ('2', 'برنزی'), ('3', 'چوبی')], default='1', max_length=1, verbose_name='نوع قالب')),
                ('max_power', models.IntegerField(default=0, verbose_name='حداکثر توان قابل کسب')),
                ('max_food', models.IntegerField(default=0, verbose_name='حداکثر آذوقه قابل کسب')),
                ('chance', models.IntegerField(default=0, verbose_name='فرصت استفاده')),
            ],
            options={
                'verbose_name': 'قالب فعالیت',
                'verbose_name_plural': 'قالب\u200cهای فعالیت\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='manzel',
            options={'verbose_name': 'منزل', 'verbose_name_plural': 'منزل\u200cها'},
        ),
        migrations.CreateModel(
            name='Activity_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان فعالیت')),
                ('file', models.FileField(blank=True, null=True, upload_to='base/static/activity/', verbose_name='فایل توضیحات فعالیت')),
                ('manzel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_topics', to='base.manzel', verbose_name='منزل')),
            ],
            options={
                'verbose_name': 'موضوع فعالیت',
                'verbose_name_plural': 'موضوعات فعالیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='base/static/activity/', verbose_name='فایل')),
                ('state', models.CharField(choices=[('1', 'ارسال شده'), ('2', 'در حال داوری'), ('3', 'داوری شده')], default='1', max_length=1, verbose_name='وضعیت')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='base.masir_group', verbose_name='گروه')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='base.activity_template', verbose_name='قالب')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='base.activity_topic', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'قالب فعالیت',
                'verbose_name_plural': 'قالب\u200cهای فعالیت\u200cها',
            },
        ),
    ]
