# Generated by Django 3.2 on 2022-04-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20220411_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='پرسش پیش\u200cفرض', max_length=500, verbose_name='متن پرسش')),
                ('answer', models.TextField(default='پاسخ پیش\u200cفرض', max_length=500, verbose_name='متن پاسخ')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش\u200cهای پرتکرار',
            },
        ),
    ]
