# Generated by Django 3.2 on 2022-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20220411_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzel',
            name='max_import_food',
            field=models.IntegerField(default=0, verbose_name='حداکثر آذوقه قابل حمل در ورودی منزل'),
        ),
        migrations.AlterField(
            model_name='activity_template',
            name='type',
            field=models.CharField(choices=[('1', 'طلایی'), ('2', 'سنگی'), ('3', 'چوبی')], default='1', max_length=1, verbose_name='نوع قالب'),
        ),
    ]
