# Generated by Django 3.2 on 2022-04-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20220412_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manzel',
            old_name='max_import_food',
            new_name='max_export_food',
        ),
    ]
