# Generated by Django 3.2 on 2022-04-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_rename_max_import_food_manzel_max_export_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group_and_exams_rel',
            name='show_public',
            field=models.BooleanField(default=False, verbose_name='نمایش عمومی'),
        ),
    ]
