# Generated by Django 3.2 on 2022-04-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_trash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trash',
            options={'verbose_name': 'اسراف', 'verbose_name_plural': 'اسراف\u200cها'},
        ),
        migrations.RemoveField(
            model_name='masir_group',
            name='achivements',
        ),
        migrations.CreateModel(
            name='Masir_Group_And_Achivements_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('achivement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base.achivement', verbose_name='دستاورد')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط میان گروه\u200cها و دستاوردها',
            },
        ),
    ]
