# Generated by Django 3.2 on 2022-04-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20220412_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='manzel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achivements', to='base.manzel', verbose_name='منزل'),
        ),
    ]
