# Generated by Django 3.2 on 2022-04-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_achivement_manzel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='O1',
            field=models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='O2',
            field=models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='O3',
            field=models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='O4',
            field=models.TextField(default='پاسخ پیش\u200cفرض', max_length=5000, verbose_name='گزینه 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Q',
            field=models.TextField(default='پرسش پیش\u200cفرض', max_length=5000, verbose_name='متن پرسش'),
        ),
    ]
