# Generated by Django 3.2 on 2022-04-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20220413_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.CharField(default='#', max_length=1000, verbose_name='لینک فایل'),
        ),
        migrations.AddField(
            model_name='club_file',
            name='link',
            field=models.CharField(default='#', max_length=1000, verbose_name='لینک فایل'),
        ),
    ]
