# Generated by Django 3.2 on 2022-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_club_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='code',
            field=models.CharField(default='XXX_X', max_length=100, verbose_name='کد دستاورد'),
        ),
        migrations.DeleteModel(
            name='Masir_Group_And_Achivements_Rel',
        ),
    ]
