# Generated by Django 3.2 on 2022-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20220415_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='food',
            field=models.FloatField(default=0, verbose_name='مقدار'),
        ),
    ]
