# Generated by Django 3.2 on 2022-04-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_trash_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masir_Group_And_Achivement_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('achivement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base.achivement', verbose_name='دستاورد')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط میان گروه\u200cها و دستاوردها',
            },
        ),
    ]
