# Generated by Django 3.2 on 2022-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_masir_group_and_achivement_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group_and_achivement_rel',
            name='score',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
    ]
