# Generated by Django 3.2 on 2023-04-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_merge_20230402_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manzel',
            name='file',
        ),
        migrations.AddField(
            model_name='activity_topic',
            name='code',
            field=models.CharField(blank=True, default='xxxxx', max_length=5, null=True, verbose_name='کد اکتشاف'),
        ),
        migrations.AddField(
            model_name='manzel',
            name='back_image',
            field=models.FileField(blank=True, null=True, upload_to='base/static/manzel/', verbose_name='تصویر پس زمینه منزل'),
        ),
        migrations.AddField(
            model_name='masir_group',
            name='discovered',
            field=models.ManyToManyField(blank=True, related_name='discoverd', to='base.User_Detail', verbose_name='فعالیت های اکتشاف شده'),
        ),
    ]
