# Generated by Django 3.2 on 2023-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20230402_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='discovered',
            field=models.ManyToManyField(blank=True, related_name='discoverd', to='base.Activity_Topic', verbose_name='فعالیت های اکتشاف شده'),
        ),
    ]
