# Generated by Django 3.2 on 2023-04-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20230402_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_topic',
            name='template',
            field=models.ManyToManyField(blank=True, null=True, related_name='templates', to='base.Activity_Template', verbose_name='قالب ها'),
        ),
    ]
