# Generated by Django 3.2 on 2023-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_activity_topic_co_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_topic',
            name='co_title',
            field=models.CharField(blank=True, default='عنوان پیش\u200cفرض', max_length=100, null=True, verbose_name='عنوان معرفتی'),
        ),
    ]
