# Generated by Django 3.2 on 2023-04-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_alter_activity_topic_co_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='manzel',
            field=models.IntegerField(default=0, verbose_name='منزل'),
        ),
    ]
