# Generated by Django 3.2 on 2023-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_alter_masir_group_manzel'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group',
            name='is_introduced',
            field=models.BooleanField(default=False, verbose_name='گذراندن آموزش اولیه'),
        ),
        migrations.AlterField(
            model_name='masir_group',
            name='manzel',
            field=models.IntegerField(default=0, verbose_name='منزل'),
        ),
    ]
