# Generated by Django 3.2 on 2023-04-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20230405_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='discovered',
            field=models.ManyToManyField(blank=True, related_name='discovered', to='base.Activity_Topic', verbose_name='فعالیت های اکتشاف شده'),
        ),
        migrations.CreateModel(
            name='Masir_Group_And_Activity_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.BooleanField(default=False, verbose_name='آسان')),
                ('level2', models.BooleanField(default=False, verbose_name='متوسط')),
                ('level3', models.BooleanField(default=False, verbose_name='دشوار')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock', to='base.masir_group', verbose_name='گروه')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='base.activity_template', verbose_name='قالب')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='base.activity_topic', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط میان گروه\u200cها و ماموریت ها',
            },
        ),
    ]
