# Generated by Django 3.2 on 2023-04-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_auto_20230406_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masir_Group_And_Topic_And_Template_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_template', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط میان گروه\u200cها و ماموریت ها',
            },
        ),
        migrations.RemoveField(
            model_name='activity_topic',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='activity_topic',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='activity_topic',
            name='level3',
        ),
        migrations.AddField(
            model_name='activity_template',
            name='info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='شرح'),
        ),
        migrations.DeleteModel(
            name='Masir_Group_And_Activity_Rel',
        ),
        migrations.AddField(
            model_name='masir_group_and_topic_and_template_rel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_topic', to='base.activity_template', verbose_name='قالب'),
        ),
        migrations.AddField(
            model_name='masir_group_and_topic_and_template_rel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_template', to='base.activity_topic', verbose_name='عنوان'),
        ),
    ]
