# Generated by Django 3.2 on 2023-04-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20230406_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='masir_group',
            name='unlocked',
            field=models.ManyToManyField(blank=True, related_name='unlocked', to='base.Activity_Template', verbose_name='قالب های باز شده'),
        ),
        migrations.DeleteModel(
            name='Masir_Group_And_Topic_And_Template_Rel',
        ),
    ]
