# Generated by Django 3.2 on 2023-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzel',
            name='story',
            field=models.URLField(blank=True, null=True, verbose_name='فایل داستان'),
        ),
    ]
