# Generated by Django 3.2 on 2023-04-09 00:46

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_alter_manzel_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masir_group',
            name='supergroup',
            field=models.IntegerField(default=0, verbose_name='ابرگروه'),
        ),
        migrations.CreateModel(
            name='Masir_Group_And_Event_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('answers', models.CharField(default='', max_length=50, verbose_name='پاسخ\u200cها')),
                ('show_public', models.BooleanField(default=False, verbose_name='نمایش عمومی')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base.event', verbose_name='فراخوان')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base.masir_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط میان گروه ها و فراخوان ها',
            },
        ),
    ]
