# Generated by Django 3.2 on 2023-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_auto_20230409_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Q',
            field=models.TextField(default='پرسش پیش\u200cفرض', max_length=5000, verbose_name='متن فراخوان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='نام فراخوان'),
        ),
    ]
