# Generated by Django 3.2 on 2023-04-11 05:39

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_auto_20230409_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='club_file',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='توضیحات داور'),
        ),
        migrations.AddField(
            model_name='club_file',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='رد شده'),
        ),
        migrations.AddField(
            model_name='club_file',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_judges', to='base.user_detail', verbose_name='داور باشگاه'),
        ),
        migrations.AddField(
            model_name='manzel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='club_file',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
    ]
