# Generated by Django 3.2 on 2023-04-10 18:26

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_auto_20230409_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'فعالیت', 'verbose_name_plural': 'گروه ها - فعالیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='activity_template',
            options={'verbose_name': 'قالب فعالیت', 'verbose_name_plural': 'فعالیت\u200cها - قالب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='activity_topic',
            options={'verbose_name': 'موضوع فعالیت', 'verbose_name_plural': 'فعالیت\u200cها - موضوعات'},
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'صدقه', 'verbose_name_plural': 'گروه ها - صدقات'},
        ),
        migrations.AlterModelOptions(
            name='club_file',
            options={'verbose_name': 'فایل\u200c', 'verbose_name_plural': 'گروه ها - فایل های باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='masir_group_and_achivement_rel',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'گروه ها - دستاوردها'},
        ),
        migrations.AlterModelOptions(
            name='masir_group_and_event_rel',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'گروه ها - ارتباط با فراخوان ها'},
        ),
        migrations.AlterModelOptions(
            name='masir_group_and_exams_rel',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'گروه ها - ارتباط با دانشگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام\u200c', 'verbose_name_plural': 'کاربران - پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'پرسش', 'verbose_name_plural': 'آزمون\u200cهای دانشگاه - پرسش ها'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'گزارش', 'verbose_name_plural': 'گروه ها - گزارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='trash',
            options={'verbose_name': 'اسراف', 'verbose_name_plural': 'گروه ها - اسراف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user_detail',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران - اطلاعات'},
        ),
        migrations.AddField(
            model_name='club_file',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='club_file',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
    ]
