# Generated by Django 3.2 on 2023-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20230410_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_file',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='توضیحات داور'),
        ),
        migrations.AlterField(
            model_name='club_file',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='رد شده'),
        ),
    ]
