# Generated by Django 3.2 on 2023-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20230420_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='شماره')),
                ('title', models.CharField(default='عنوان پیش\u200cفرض', max_length=100, verbose_name='عنوان')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک اثر')),
                ('type', models.CharField(choices=[('1', 'صوتی'), ('2', 'ویدیویی'), ('3', 'تصویری')], default='1', max_length=1, verbose_name='نوع اثر')),
            ],
            options={
                'verbose_name': 'عنوان اثر',
                'verbose_name_plural': 'آثار برتر',
            },
        ),
    ]
