# Generated by Django 3.2 on 2023-04-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20230410_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_file',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_judges', to='base.user_detail', verbose_name='داور باشگاه'),
        ),
    ]
