# Generated by Django 3.2 on 2023-04-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_top_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_work',
            name='title',
        ),
        migrations.AddField(
            model_name='top_work',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topworks', to='base.masir_group', verbose_name='گروه'),
        ),
    ]
