# Generated by Django 3.2 on 2023-05-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20230428_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_work',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topworks', to='base.activity_topic', verbose_name='عنوان ماموریت'),
        ),
    ]
