# Generated by Django 3.2 on 2023-04-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
