# Generated by Django 3.2 on 2023-04-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20230426_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='is_verified',
            new_name='is_valid',
        ),
    ]
