# Generated by Django 3.2 on 2023-05-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_top_work_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='score6',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='score7',
        ),
        migrations.AddField(
            model_name='activity',
            name='score_long',
            field=models.FloatField(default=0, verbose_name='امتیاز تحول'),
        ),
    ]
