# Generated by Django 3.2 on 2023-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_manzel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cheated',
            field=models.BooleanField(default=False, verbose_name='رفتن به منزل بعد قبل از داوری'),
        ),
    ]
