# Generated by Django 3.2 on 2023-04-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_rename_is_verified_vote_is_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'رای', 'verbose_name_plural': 'آرای نظرسنجی مردمی'},
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='selections',
        ),
    ]
