from django.contrib import admin
from base.models import *

admin.site.register(Message)
admin.site.register(User_Detail)
admin.site.register(Accessibility)
admin.site.register(City)
admin.site.register(School)
admin.site.register(Manzel)
admin.site.register(Announcement)
admin.site.register(Masir_Group)
admin.site.register(Club_File)
admin.site.register(Charity)
admin.site.register(Question)
admin.site.register(Exam)
admin.site.register(Masir_Group_And_Exams_Rel)
admin.site.register(Achivement)
admin.site.register(Report)
admin.site.register(Activity_Template)
admin.site.register(Activity_Topic)
admin.site.register(Activity)
admin.site.register(FAQ)
admin.site.register(Trash)
admin.site.register(Vote)
admin.site.register(Masir_Group_And_Achivement_Rel)